# Header
LOGO = ("xpath", "//header//div[contains(@class, 'text-logo')]")

EXPLORE_DROPDOWN = ("xpath", "//header//nav//a[contains(@class,'nav-link dropdown')]")
EXPLORE_TOP_TRACKS = ("xpath", "//header//nav//a[@click-event-target='Top tracks']")
EXPLORE_PYTHON = ("xpath", "//header//nav//a[@click-event-target='Python']")
EXPLORE_JAVA = ("xpath", "//header//nav//a[@click-event-target='Java']")
EXPLORE_GO = ("xpath", "//header//nav//a[@click-event-target='Go']")
PRICING_TAB = ("xpath", "//header//nav//li[@click-event-target='pricing']")
FOR_BUSINESS_TAB = ("xpath", "//header//nav//li[@click-event-target='join_as_organization']")
SIGN_IN_BUTTON = ("xpath", "//header//nav//button[contains(@class,'btn btn-outline')]")
START_FOR_FREE_BUTTON = ("xpath", "//header//nav//button[contains(@class,'btn btn-primary')]")

# Body
TOP_TRACKS_TAB = ("xpath", "//main//div[@data-component-name='TrackCategories']/a[text()='Top tracks ']")
GO_TAB = ("xpath", "//main//div[@data-component-name='TrackCategories']/a[text()='Go ']")
PYTHON_TAB = ("xpath", "//main//div[@data-component-name='TrackCategories']/a[text()='Python ']")
ANDROID_TAB = ("xpath", "//main//div[@data-component-name='TrackCategories']/a[text()='Android ']")
PYTHON_CORE_COURSE = ("xpath", "//main//div[@data-component-name='TransitionGroup']/a[@aria-label='Python Core']")
INTRODUCTION_TO_PYTHON_COURSE = ("xpath", "//main//div/a[@aria-label='Introduction to Python']")
KOTLIN_CORE_COURSE = ("xpath", "//main//div[@data-component-name='TransitionGroup']/a[@aria-label='Kotlin Core']")
INTRODUCTION_TO_JAVA_COURSE = ("xpath", "//main//div/a[@aria-label='Introduction to Java']")

# Footer
TOP_TRACKS = ("xpath", "//footer//a[@click-event-target='Top tracks']")
PYTHON = ("xpath", "//footer//a[@click-event-target='Python']")
JAVA = ("xpath", "//footer//a[@click-event-target='Java']")
KOTLIN = ("xpath", "//footer//a[@click-event-target='Kotlin']")
REDDIT_LINK_ICON = ("xpath", "//footer//a[@title='Hyperskill on Reddit']")
FACEBOOK_LINK_ICON = ("xpath", "//footer//a[@click-event-target='Facebook']")
LINKEDIN_LINK_ICON = ("xpath", "//footer//a[@click-event-target='Linkedin']")
DISCORD_LINK_ICON = ("xpath", "//footer//a[@click-event-target='Discord']")
BLOG = ("xpath", "//footer//a[@click-event-target='blog']")
UNIVERSITY = ("xpath", "//footer//a[@click-event-target='university']")
GOOGLE_PLAY_BUTTON = ("xpath", "//footer//a[@click-event-target='google-play']")
APP_STORE_BUTTON = ("xpath", "//footer//a[@click-event-target='app-store']")
